challenge/config/routes.rb
Rails.application.routes.draw do

  get 'questions/index'
  get 'questions/decision/:id/:decision' => "questions#decision", :as => :decision
  get 'questions/result'
  get 'questions/error'
  root 'welcome#index'

end

challenge/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions
end

challenge/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category

  def self.not_included_in(answered_questions)
    where('id NOT IN(?)', answered_questions).sample
  end

end

challenge/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_filter :load_dog_counter, :load_cat_counter, :load_questions
  after_filter :save_dog_counter, :save_cat_counter, :save_questions

  private

  def load_dog_counter
    @dog_counter = session[:dog_counter] ||= 0
  end

  def save_dog_counter
    session[:dog_counter] = @dog_counter
  end

  def load_cat_counter
    @cat_counter = session[:cat_counter] ||= 0
  end

  def save_cat_counter
    session[:cat_counter] = @cat_counter
  end

  def load_questions
    @answered_questions = session[:answered_questions] ||= []
  end

  def save_questions
    session[:answered_questions] = @answered_questions
  end

end

challenge/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    begin
      @question = if @answered_questions.length > 0
        Question.not_included_in(@answered_questions)
      else
        Question.all.sample
      end
      @answered_questions << @question.id
      @text = @question.body
      @current_id = @question.category_id
    rescue NoMethodError
      redirect_to action: 'error', status: 303
    end
  end

  def decision
    @id = params[:id].to_i
    @decision = params[:decision]
    if @id == 2 && @decision == "yes" || @id == 1 && @decision == "no"
      @dog_counter += 1
    elsif @id == 1 && @decision == "yes" || @id == 2 && @decision == "no"
      @cat_counter += 1
    end
    if @answered_questions.length == 3
      redirect_to action: 'result', status: 303
    else
      redirect_to action: 'index', status: 303
    end
  end

  def result
    if @dog_counter > @cat_counter
      @message = "...like dogs more than anything else!"
    elsif @dog_counter < @cat_counter
      @message = "...love cats more than anything else!"
    else @dog_counter = @cat_counter
      @message = "...are more of a plant person."
    end
  end

  def error
  end

end

challenge/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @cat_counter = 0
    @dog_counter = 0
    @answered_questions = []
  end

end

challenge/app/helpers/application_helper.rb
module ApplicationHelper
end

challenge/app/helpers/questions_helper.rb
module QuestionsHelper
end

challenge/app/helpers/welcome_helper.rb
module WelcomeHelper
end

challenge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Challenge</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= yield %>

	</body>
</html>

challenge/app/views/questions/error.html.erb
<h1>Wooops...</h1>
	<p><div class="text">Please don't refresh the browser. This only confuses your test result!</p>
	<p>Now you will have to start from the beginning.</div></p>
	<p><%= link_to "I'm sorry", root_path, :class => "button" %></p>

challenge/app/views/questions/index.html.erb
<h1>Please answer honestly:</h1>
	<p>
		<div class="question"><%= @text %></div>
	</p>
	<div class="wrap">
		<%= link_to "YES", decision_path(:id => @current_id, :decision => "yes"), :class => "button" %>
		<%= link_to "NO", decision_path(:id => @current_id, :decision => "no"), :class => "button" %>
	</div>

challenge/app/views/questions/result.html.erb
<h1>Congratulations! You know now that you...</h1>
	<p><div class="question"><%= @message %></div><p>
	<p><%= link_to "AGAIN", root_path, :class => "button" %></p>

challenge/app/views/welcome/index.html.erb
<h1>Welcome to the personality check!</h1>
	<p>
		<div class="text">You always wanted to know what kind of person you are? It's been bothering you how other people just know whether they like cats more or dogs, and you up to now just couldn't decide? Well, this test is your salvation! After three simple questions you will know whether you are more the cat type or the dog type.</div>
	</p>
	<p>
		<%= link_to 'START', questions_index_path, :class => "button" %>
	</p>